seed: 123
graph_sizes: [10, 30, 50, 100]
graph_types: ['undirected', 'directed']
K: 3
shared_params:
  hidden_dim: 32
  output_dim: 1
  dropout: 0.1
  normalization: "sym"
  num_layers: 4
  num_epochs: 100
  learning_rate: 0.01
  device: "cpu"
